[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "sergio_rs"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Programming Language :: Rust",
]
dynamic = ["version"]
dependencies = ["polars>=1.36.1", "numpy>=2.4.0"]

[tool.maturin]
features = ["extension-module"]

[tool.maturin.generate-ci.github]
args = "--locked"
pytest = false
trusted-publishing = false

[tool.maturin.generate-ci.github.linux]
runner = "ubuntu-24.04"
manylinux = "2_28"
targets = ["x86_64", "aarch64"]
rust-toolchain = "1.98.1"

[tool.maturin.generate-ci.github.windows]
rust-toolchain = "1.98.1"

[[tool.maturin.generate-ci.github.windows.target]]
arch = "x64"
runner = "windows-2025"

[[tool.maturin.generate-ci.github.windows.target]]
arch = "aarch64"
runner = "windows-11-arm"

[tool.maturin.generate-ci.github.macos]
rust-toolchain = "1.98.1"

[[tool.maturin.generate-ci.github.macos.target]]
arch = "x86_64"
runner = "macos-15-intel"

[[tool.maturin.generate-ci.github.macos.target]]
arch = "aarch64"
runner = "macos-26"
